algoritmo "questao_10"
// Função :
// Autor :
// Data : 19/03/2016
// Seção de Declarações 
var
// Faça um algoritmo que leia dois vetores (A e B) de 50 posições de números
//O algoritmo deve, entao somar o pimeiro elemento de A do último de B, acumulado
//o valor em um outro vetor, somar o segundo elemento de A do penúltimo de B
//acumulado o valor, e assim por diante. Mostre o resultado final.
inicio
// Seção de Comandos 
fimalgoritmo
