algoritmo "exercicio3_1"
//1-Faça um algoritmo que leia quatro números inteiros e mostre a soma deles:
var
n1,n2,n3,n4,soma:inteiro
inicio
escreval("Informe 4 valores inteiros;")
escreval("Informe o valor do primeiro numero;")
leia(n1)
escreval("Informe o valor do segundo numero:")
leia(n2)
escreval("Informe o valor do terceiro numero:")
leia(n3)
escreval("Informe o valor do quarto numero:")
leia(n4)
soma<-n1+n2+n3+n4
escreval("O valor da soma e:",soma)
fimalgoritmo
