algoritmo "lista1_h"// Nome do algoritmo
var
//Variaveis declarada: num, quinta_parte
// Tipo de dado Real
num, quinta_parte: real
inicio
// Seção de Comandos
escreval("Calcule a quinta parte de um numero:")//Informação ao usuario
escreval("")
escreval("Informe um valor...")//Entrada de dados
escreva("==> ")
leia(num)
//processamento
quinta_parte<-(num/5)
//Saida de dados
escreval("A quinta parte do numero informado é ==> ",quinta_parte)
fimalgoritmo
