algoritmo "Lista2_1"
var
num, r1, r2:real

inicio
escreval("Entrar com um número e imprimir a seguinte saida:")// Seção de Comandos
escreval("Numero:")
escreval("Quadrado:")
escreval("Raiz Quadrada:")
escreval("")
escreval("*----------------------------*")
escreval("")
escreval("Entre com o numero")
leia(num)
r1<-(num^2)
r2<-(r1/num)
escreval(" O numero informado foi: ",num)
escreval(" O quadrado de ",num," é: ",r1)
escreval(" A raiz de ",r1," é: ",r2)
fimalgoritmo
